language: node_js
node_js: 5.0.0
install: npm install
services: mongodb
deploy:
	provider: heroku
	api_key:
		secure: RVnhcP806ZDfOvlsKLPlCUQfPJSrPZXXUzhMlRrDCYigg4dN5yZtQ4YLz/cS0OjLKpAimfPRMS7L4687CDC7zTHT3T55YXR4vTCiTQd1oukHzEFLXSzASO2NXQCHDVRRPnaojf7PSIgvedlpblIBBYT/9pb0YscrfkZpiPBssCK0BQ6BFvoZNsYQIukUPkzedNHOF4JWmR7lMufisjTaxs5Apf/98IKsFcmRqBHfdBdtrp2TQvcJOwQ1btuWgkBS+OTYMPUGw45uXjve72J+zGxcRDzLbZU83+g9NN6E4oX1+oaxXmZLL8yZMJtOOZUpV+Dw5zeeDTzvFN4wuzBPTzB+Nzz6ubSNPfhwnvggYZfiV7RlHZtCCKvgfLb+KLolrRvQHrZwrGfAieFc1pUQDoY5yNqGUN9uzAI9DiE2lajl/VZcoJQyLcmrhFNtuqhNNOkiZyUKNZOZzUNnGXsbQ5n2TIgqyXvVDK9LEkTm+1G/ez2ofWM364S5Au7I9VpFMgt3Lth3eZN050x8UMWBLtvRDC86iJ/GoJYRluoKJbVOvYFW62qR8uOcE+fKlJBneNsqV7FwcLlTUVflRPjEVF96Z0dPbZnXq+YJfH1L98PPKF4q1ZvIqdO1Mx/FfatN38BwvuqvfTWily9eAnTHn0E8dICalNrL3Kwg0zeZFz0=
	app:
		dev: songlink-staging
		production: songlink-production
